import Ember from 'ember';
export
default Ember.Route.extend({
  setupController: function(controller, model) {
    this._super(controller, model);

    // FIXXME: get from SDA service!
    // FIXXME: create Queries model to enable saving and linking into session model!
    var queries = [Ember.Object.create({
      label: 'Buildings completed in 1931',
      description: " Retrieve all information on buildings completed in the year 1931. The query uses metadata from an semantic enrichement containing the YAGO categories.",
      candidates: { "head": { "link": [], "vars": ["buildingName"] },
  "results": { "distinct": false, "ordered": true, "bindings": [
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Aldred_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Allen_Hazen_Water_Tower" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Allied_Arts_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Americanization_School" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Andrews_Geyser" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Big_Duck" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Blue_Anchor_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Boerentoren" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Boji_Tower" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Brill_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Buenos_Aires_City_Legislature" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/C.A._Schnack_Jewelry_Company_Store" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Capitol_Theatre,_Manchester" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Carew_Tower" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chestertown_Armory" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Commerce_Court" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Communal_House_of_the_Textile_Institute" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Crane_Flat_Fire_Lookout" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/De_Anza_Hotel" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/DuMont_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/East_Cambridge_Savings_Bank" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Enchanted_Valley_Chalet" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/First_Oil_Well,_Bahrain" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/General_Electric_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Grand_Hotel_Toplice" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/H.B._Burns_Memorial_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Hotel_Clovis" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Hotel_Torni" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Hunt's_Tomb" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Imperial_Chemical_House" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/India_of_Inchinnan" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Jerome_First_Baptist_Church" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/John_Stickel_House" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/John_Street_Roundhouse" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Las_Ventas" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Linden_Hills_Community_Library" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Matchstick_Palace" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/McKenzie_Windmill" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Nampa_American_Legion_Chateau" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/National_Bank_of_Rolla_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/National_Newark_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/New_Haven_Lawn_Club" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/North_Shore_Sanitary_District_Tower" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Oatman_Filling_Station" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Pair-O-Dice" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Palacio_Minetti" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Parliament_House,_Helsinki" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Powers_Auditorium" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Prudential,_Warsaw" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Pulaski_Library" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Red_Crown_Tourist_Court" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Reservoir_Avenue_Sewage_Pumping_Station" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Saint_Paul_Municipal_Grain_Terminal" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Santamar%C3%ADa_Bullring" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Scalplock_Mountain_Fire_Lookout" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Sea_Cliff_Firehouse" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Sedgwick_Gardens" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Shell_Mex_House" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Sinnott_Memorial_Observation_Station" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Skoki_Ski_Lodge" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Southern_New_England_Telephone_Company_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Sprague's_Super_Service" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Springdale_School" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Sun_Life_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Sunset_Park_Trail_Shelter" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Sunset_Tower" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Sylvan_Theater_Historic_District" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Tahoma_Vista_Comfort_Station" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Timber_Creek_Road_Camp_Barn" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Tioga_Pass_Entrance_Station" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Torre_Jaume_I" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Tower_Petroleum_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Tulsa_Fire_Alarm_Building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Upper_Kintla_Lake_Patrol_Cabin" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Van_Nelle_Factory" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Walnut_Creek_Ranger_Station" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/West_Side_Sanitarium" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Zarya_Vostoka_building" }	, "type": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "value": { "type": "uri", "value": "http://dbpedia.org/class/yago/BuildingsAndStructuresCompletedIn1931" }} ] } },
    }),Ember.Object.create({
      label: 'Skyscrapers in Manhatten',
      description: "Retrieve all information on skyscrapers in Manhatten.",
      candidates: { "head": { "link": [], "vars": ["buildingName"] },
  "results": { "distinct": false, "ordered": true, "bindings": [
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/American_Radiator_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/American_Stock_Exchange" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Asser_Levy_Public_Baths" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Association_Residence_Nursing_Home" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bayard-Condict_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Broad_Exchange_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chanin_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Corbin_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Daily_News_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/DeVinne_Press_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Duffy_Square" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Federation_of_Protestant_Welfare_Agencies" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Film_Center_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Flatiron_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Former_Emigrant_Industrial_Savings_Bank" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Former_New_York_Life_Insurance_Company_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Fred_F._French_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/GE_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/General_Electric_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Gilsey_House" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Gouverneur_Hospital" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Henry_Street_Settlement" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/International_House_of_New_York" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Lever_House" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Metropolitan_Life_Insurance_Company_Tower" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/New_York_Amsterdam_News_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/New_York_Life_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Old_New_York_Evening_Post_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Park_Row_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Puck_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Robbins_&_Appleton_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Rockefeller_Center" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Seagram_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Sheffield_Farms_Stable" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Society_for_the_Lying-In_Hospital" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/United_Charities_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/University_Settlement_Society_of_New_York" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Verizon_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Westbeth_Artists_Community" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Adam_Clayton_Powell_Jr._State_Office_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/American_Radiator_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Brill_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bush_Tower" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Flatiron_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Ford_Foundation_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/GE_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Gorham_Manufacturing_Company" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Hotel_Theresa" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Lefcourt_Colonial_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Lipstick_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Manhattan_Municipal_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Marbridge_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/MetLife_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Metropolitan_Life_North_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Morgan_Stanley_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/New_York_Merchandise_Mart" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Paramount_Plaza" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Parker_Building,_New_York_City" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Pershing_Square_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Prudence_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Puck_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Scholastic_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/The_New_York_Times_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Verizon_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/W._R._Grace_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Woolworth_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/World_Financial_Center" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/World_Trade_Center" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/2009%E2%80%9310_Syracuse_Orange_men's_basketball_team" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Rockefeller_Center" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Central_Park" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Chelsea,_Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Broadway_theatres" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Theater_District,_New_York" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Times_Square" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Pennsylvania_Plaza" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Hell's_Kitchen,_Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Kips_Bay,_Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Rose_Hill,_Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Flatiron_District" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Gramercy,_Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Columbus_Circle" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Empire_State_Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Rockefeller_Center" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Residential_skyscrapers_in_Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Churches_in_Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Hotels_in_Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Parks_in_Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Museums_in_Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:National_Register_of_Historic_Places_in_Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Universities_and_colleges_in_Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Category:Synagogues_in_Manhattan" }} ] } }
  }),
  Ember.Object.create({
  label: 'Population statistics for buildings in "Stanley, Idaho"',
  description: 'This query enriches all buildings located in "Stanley, Idaho" with population statistics from "DBpedia".',
  candidates: { "head": { "link": [], "vars": ["buildingName", "geoLoc"] },
    "results": { "distinct": false, "ordered": true, "bindings": [
      { "buildingName": { "type": "uri", "value": "http://data.duraark.eu/resource/0648577" }	, "geoLoc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
      { "buildingName": { "type": "uri", "value": "http://data.duraark.eu/resource/0664795" }	, "geoLoc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
      { "buildingName": { "type": "uri", "value": "http://data.duraark.eu/resource/0723948" }	, "geoLoc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
      { "buildingName": { "type": "uri", "value": "http://data.duraark.eu/resource/Beatrijsweg15" }	, "geoLoc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
      { "buildingName": { "type": "uri", "value": "http://data.duraark.eu/resource/CottageHouseMnichovice" }	, "geoLoc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
      { "buildingName": { "type": "uri", "value": "http://data.duraark.eu/resource/FamilyHouse" }	, "geoLoc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
      { "buildingName": { "type": "uri", "value": "http://data.duraark.eu/resource/JacobCatstraat16" }	, "geoLoc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
      { "buildingName": { "type": "uri", "value": "http://data.duraark.eu/resource/OuderlijkHuis" }	, "geoLoc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
      { "buildingName": { "type": "uri", "value": "http://data.duraark.eu/resource/Seychelles" }	, "geoLoc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }} ] } }
}),Ember.Object.create({
  label: '"Art Deco" buildings',
  description: 'Searches for buildings in the SDAS designed by "Ludwig Hoffmann"',
  candidates: { "head": { "link": [], "vars": ["buildingName", "architect", "o"] },
  "results": { "distinct": false, "ordered": true, "bindings": [
    { "buildingName": { "type": "uri", "value": "Haus_30" }	, "architect": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "o": { "type": "uri", "value": "http://www.w3.org/2002/07/owl#NamedIndividual" }},
    { "buildingName": { "type": "uri", "value": "Haus_30" }	, "architect": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "o": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/PhysicalAsset" }},
    { "buildingName": { "type": "uri", "value": "Haus_30" }	, "architect": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/architect" }	, "o": { "type": "literal", "value": "Ludwig Hoffmann" }},
    { "buildingName": { "type": "uri", "value": "Haus_30" }	, "architect": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/buildingCount" }	, "o": { "type": "literal", "value": "1" }},
    { "buildingName": { "type": "uri", "value": "Haus_30" }	, "architect": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/addressLocality" }	, "o": { "type": "literal", "value": "Berlin" }},
    { "buildingName": { "type": "uri", "value": "Haus_30" }	, "architect": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/name" }	, "o": { "type": "literal", "value": "Haus 30" }} ] } }
}),Ember.Object.create({
  label: 'Information on buildings in Manhatten',
  description: 'Searches for information on buildings in Manhatten, including their number or floors.',
  candidates: { "head": { "link": [], "vars": ["buildingName", "p", "floors"] },
  "results": { "distinct": false, "ordered": true, "bindings": [
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }	, "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "floors": { "type": "uri", "value": "http://www.w3.org/2002/07/owl#NamedIndividual" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }	, "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "floors": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/PhysicalAsset" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Empire_State_Building" }	, "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "floors": { "type": "uri", "value": "http://www.w3.org/2002/07/owl#NamedIndividual" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Empire_State_Building" }	, "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "floors": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/PhysicalAsset" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Woolworth_Building" }	, "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "floors": { "type": "uri", "value": "http://www.w3.org/2002/07/owl#NamedIndividual" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Woolworth_Building" }	, "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "floors": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/PhysicalAsset" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bank_of_America_Tower" }	, "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "floors": { "type": "uri", "value": "http://www.w3.org/2002/07/owl#NamedIndividual" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bank_of_America_Tower" }	, "p": { "type": "uri", "value": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" }	, "floors": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/PhysicalAsset" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/architect" }	, "floors": { "type": "literal", "value": "William Van Alen" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Empire_State_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/architect" }	, "floors": { "type": "literal", "value": "Shreve, Lamb and Harmon" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Woolworth_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/architect" }	, "floors": { "type": "literal", "value": "Cass Gilbert" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bank_of_America_Tower" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/architect" }	, "floors": { "type": "literal", "value": "Cookfox" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/buildingArea" }	, "floors": { "type": "literal", "value": "111019.132800" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Empire_State_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/buildingArea" }	, "floors": { "type": "literal", "value": "208879.014499" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bank_of_America_Tower" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/buildingArea" }	, "floors": { "type": "literal", "value": "195096.384000" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/buildingCount" }	, "floors": { "type": "literal", "value": "1" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Empire_State_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/buildingCount" }	, "floors": { "type": "literal", "value": "1" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Woolworth_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/buildingCount" }	, "floors": { "type": "literal", "value": "1" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bank_of_America_Tower" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/buildingCount" }	, "floors": { "type": "literal", "value": "1" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/completionDate" }	, "floors": { "type": "literal", "value": "1930" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Empire_State_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/completionDate" }	, "floors": { "type": "literal", "value": "1931" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Woolworth_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/completionDate" }	, "floors": { "type": "literal", "value": "1913" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bank_of_America_Tower" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/completionDate" }	, "floors": { "type": "literal", "value": "2009" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Empire_State_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/cost" }	, "floors": { "type": "literal", "value": "4.09489E7" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/startDate" }	, "floors": { "type": "literal", "value": "1928" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Empire_State_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/startDate" }	, "floors": { "type": "literal", "value": "1929" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Woolworth_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/startDate" }	, "floors": { "type": "literal", "value": "1910" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bank_of_America_Tower" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/startDate" }	, "floors": { "type": "literal", "value": "2004" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/addressLocality" }	, "floors": { "type": "literal", "value": "Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Empire_State_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/addressLocality" }	, "floors": { "type": "literal", "value": "Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Woolworth_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/addressLocality" }	, "floors": { "type": "literal", "value": "Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bank_of_America_Tower" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/addressLocality" }	, "floors": { "type": "literal", "value": "Manhattan" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/floorCount" }	, "floors": { "type": "literal", "value": "77" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Empire_State_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/floorCount" }	, "floors": { "type": "literal", "value": "103" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Woolworth_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/floorCount" }	, "floors": { "type": "literal", "value": "57" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bank_of_America_Tower" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/floorCount" }	, "floors": { "type": "literal", "value": "55" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/name" }	, "floors": { "type": "literal", "value": "Chrysler Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Empire_State_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/name" }	, "floors": { "type": "literal", "value": "Empire State Building" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Woolworth_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/name" }	, "floors": { "type": "literal", "value": "Cass Gilbert" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bank_of_America_Tower" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/name" }	, "floors": { "type": "literal", "value": "Bank of America Tower" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Chrysler_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/architectureStyle" }	, "floors": { "type": "literal", "value": "Art Deco" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Empire_State_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/architectureStyle" }	, "floors": { "type": "literal", "value": "Art Deco" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Woolworth_Building" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/architectureStyle" }	, "floors": { "type": "literal", "value": "Art Deco" }},
    { "buildingName": { "type": "uri", "value": "http://dbpedia.org/resource/Bank_of_America_Tower" }	, "p": { "type": "uri", "value": "http://data.duraark.eu/vocab/buildm/architectureStyle" }	, "floors": { "type": "literal", "value": "Art Deco" }} ] } }
}),Ember.Object.create({
  label: 'Geonames Enrichment Example',
  description: 'Example query to enrich SDAS resource with locations from Geonames.',
  candidates: { "head": { "link": [], "vars": ["building", "geoloc"] },
  "results": { "distinct": false, "ordered": true, "bindings": [
    { "building": { "type": "uri", "value": "http://data.duraark.eu/resource/0648577" }	, "geoloc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
    { "building": { "type": "uri", "value": "http://data.duraark.eu/resource/0664795" }	, "geoloc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
    { "building": { "type": "uri", "value": "http://data.duraark.eu/resource/0723948" }	, "geoloc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
    { "building": { "type": "uri", "value": "http://data.duraark.eu/resource/Beatrijsweg15" }	, "geoloc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
    { "building": { "type": "uri", "value": "http://data.duraark.eu/resource/CottageHouseMnichovice" }	, "geoloc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
    { "building": { "type": "uri", "value": "http://data.duraark.eu/resource/FamilyHouse" }	, "geoloc": { "type": "uri", "value": "http://sws.geonames.org/256861/" }},
    { "building": { "type": "uri", "value": "http://data.duraark.eu/resource/JacobCatstraat16" }	, "geoloc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
    { "building": { "type": "uri", "value": "http://data.duraark.eu/resource/OuderlijkHuis" }	, "geoloc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }},
    { "building": { "type": "uri", "value": "http://data.duraark.eu/resource/Seychelles" }	, "geoloc": { "type": "uri", "value": "http://sws.geonames.org/4951935/" }} ] } }
})];



    // FIXXME: incorporate selected topics from session!
    queries.forEach(function(query) {
      query.set('isSelected', false);
    });

    controller.set('queries', queries);

    this.send('setTitle', 'Explore Knowledge Graph');

    var appState = this.modelFor('application');
    controller.set('knowledgeState', appState.get('knowledge'));
  }

});
